### ISSUE TITLE
Make available as a CocoaPods pod

### ISSUE THREAD

**Issue by alphastryk** [uber/UberSignature#3]
Making this available as a pod would make it much easier to implement and integrate into other projects

**Comment by akmarinov** [comment]
@alphastryk I've forked it and created a podspec

You can integrate with Cocoapods via

`pod 'UberSignature', :git => 'https://github.com/akmarinov/UberSignature.git'`

**Comment by alanzeino** [comment]
We have an official podspec now:

https://cocoapods.org/pods/UberSignature
