### ISSUE TITLE
Official package distribution

### ISSUE THREAD

**Issue by adamrothman** [uber/UberSignature#8]
I see this has already been brought up in #3 but I'd like to raise it again. IMO a 3rd-party fork with a Podfile isn't a great solution as 1) it's already out of date with this repo and 2) it's not in the official package index. UberSignature is an awesome repo – let's make it easier for more people to install and use in their projects!

@myhrvold @viralplatipuss @jmascia is this something you'd be willing to support? I'd be happy to submit a PR with a `Podspec` if you guys are on board to publish it to https://cocoapods.org/. It would also be great to support installation via Carthage.

**Comment by 4brunu** [comment]
It would be awesome to have at least CocoaPods support.
I would also be available to help with this.

**Comment by viralplatipuss** [comment]
I no longer work at Uber, but seeing if I can get someone to look into adding this.

**Comment by alanzeino** [comment]
I'll have a go

**Comment by alanzeino** [comment]
Published on CocoaPods.

https://cocoapods.org/pods/UberSignature

**Comment by adamrothman** [comment]
Thanks @alanzeino!
