### ISSUE TITLE
Reduce the minimum iOS supported version

### ISSUE THREAD

**Issue by 4brunu** [uber/UberSignature#9]
While adding support for CocoaPods (https://github.com/uber/UberSignature/issues/8), the minimum iOS supported version was raised from 8.0 to 11.4.

I'm not sure if this was an intentional change, but I need to support iOS 10.0.

@alanzeino can we set a lower minimum iOS supported version?

Thanks

**Comment by alanzeino** [comment]
Cool, just pushed version 1.0.3. It has a deployment target of iOS `10.0`, the lowest version we support at Uber.
